<?php include __DIR__ . '/header.phtml'; ?>
    <div class="container">
        <div class="entry-list single">
        <?php
            // check for empty set
            if (empty($posts)) {
                echo 'Sorry. This post you requested isn\'t here.';
            // echo out blog post
            } else {
                echo '<article>';
                    echo "<h2>" . $posts[0]['title'] . "</h2>";
                    echo "<time datetime=\"" . $posts[0]['date'] . "\">" . date('F j, Y \a\t H:i',strtotime($posts[0]['date'])) . '</time>';
                    echo "<div class=\"entry\">";
                        echo $posts[0]['body'];
                        echo "<p><a class=\"link\" href=\"/edit/" . $posts[0]['id'] . "\">Edit Entry</a></p>";
                    echo "</div>";
                echo '</article>';
            }
        ?>
        </div>
    </div>
</section>
<section class="entry-comments">
    <div class="container">
            <h2>Comments</h2>
            <?php 
                // check for comments
                if (empty($comments)) {
                    echo 'No comments have been made on this post';
                //echo out comments
                } else {
                    foreach ($comments as $comment) {
                        echo '<div class="comment">';
                            echo '<strong>' . $comment['name'] . '</strong>';
                            echo '<time datetime="' . $comment['date_time'] . '">' . date('F j, Y \a\t H:i',strtotime($comment['date_time'])) . '</time>';
                            echo $comment['body'];
                        echo '</div>';
                    }
                }
            ?>
            
            <div class="new-comment">
                <form>
                        <label for="name"> Name</label>
                        <input type="text" name="name"><br>
                        <label for="comment">Comment</label>
                        <textarea rows="5" name="comment"></textarea>
                        <input type="submit" value="Post Comment" class="button">
                </form>
            </div>
    </div>
<?php include __DIR__ . '/footer.phtml'; ?>