<?php include __DIR__ . '/header.phtml'; ?>
    <div class="container">
        <div class="entry-list single">
        <?php
            // check for empty set
            if (empty($posts)) {
                echo 'Sorry. This post you requested isn\'t here.';
            // echo out blog post
            } else {
                echo '<article>';
                    echo "<h2>" . $posts['title'] . "</h2>";
                    echo "<time datetime=\"" . $posts['date'] . "\">" . date('F j, Y \a\t H:i',strtotime($posts['date'])) . '</time>';
                    echo "<div class=\"entry\">";
                        echo $posts['body'];
                        echo "<p><a class=\"link\" href=\"/edit/" . $posts['id'] . "\">Edit Entry</a></p>";
                    echo "</div>";
                echo '</article>';
            }
        ?>
        </div>
    </div>
</section>
<section class="entry-comments">
    <div class="container">
            <h2>Comments</h2>
            <?php 
                // check for comments
                if (condition) {
                //     echo 'No comments have been made on this post';
                // //echo out comments
                // } else {
                    echo '<div class="comment">';
                        echo '<strong>Carling Kirk</strong>';
                        echo '<time datetime="2016-01-31 1:00">January 31, 2016 at 1:00</time>';
                        echo '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut rhoncus felis, vel tincidunt neque. Vestibulum ut metus eleifend, malesuada nisl at, scelerisque sapien. Vivamus pharetra massa libero, sed feugiat turpis efficitur at.</p>';
                    echo '</div>';
                }
            ?>
            
            <div class="new-comment">
                <form>
                        <label for="name"> Name</label>
                        <input type="text" name="name"><br>
                        <label for="comment">Comment</label>
                        <textarea rows="5" name="comment"></textarea>
                        <input type="submit" value="Post Comment" class="button">
                </form>
            </div>
    </div>
<?php include __DIR__ . '/footer.phtml'; ?>