<?php include __DIR__ . '/header.phtml'; ?>
    <div class="container">
        <div class="entry-list">
            <article>
                <h2><a href="/blog/<?php echo $args['id']; ?>"><?php echo $title ?></a></h2>
                <time datetime="<?php echo $args['date']; ?>"><?php echo $args['date']; ?></time>
            </article>
        
            <article>
                <h2><a href="/blog/1">The best day I’ve ever had</a></h2>
                <time datetime="2016-01-31 1:00">January 31, 2016 at 1:00</time>
            </article>
            <article>
                <h2><a href="/blog/2">The absolute worst day I’ve ever had</a></h2>
                <time datetime="2016-01-31 1:00">January 31, 2016 at 1:00</a></time>
            </article>
            <article>
                <h2><a href="/blog/3">That time at the mall</a></h2>
                <time datetime="2016-01-31 1:00">January 31, 2016 at 1:00</a></time>
            </article>
            <article>
                <h2><a href="/blog/4">Dude, where’s my car?</a></h2>
                <time datetime="2016-01-31 1:00">January 31, 2016 at 1:00</a></time>
            </article>
        </div>
    </div>
<?php include __DIR__ . '/footer.phtml'; ?>