<?php include __DIR__ . '/header.phtml'; ?>
    <div class="container">
        <div class="new-entry">
            <h2>Publish New Entry</h2>
            <form method="post" action="">
                <label for="title"> Title</label>
                <input type="text" name="title" value="<?php if(isset($_POST['title'])){ echo $_POST['title'];} ?>"><br>
                <label for="entry">Entry</label>
                <textarea rows="5" name="body"><?php if(isset($_POST['body'])){ echo $_POST['body'];} ?></textarea>
                <input type="submit" value="Publish Entry" class="button">
                <a href="#" class="button button-secondary">Cancel</a>
                <?php foreach ($csrf as $key=>$value){
                    echo "<input type=\"hidden\" name=\"$key\" value=\"$value\">";
                } ?>
            </form>
        </div>
    </div>
<?php include __DIR__ . '/footer.phtml'; ?>