<?php include __DIR__ . '/header.phtml'; ?>
    <div class="container">
        <div class="password">
            <form>
                <label for="password">Enter Password</label>
                <input type="password" name="password"><br>
                <input type="submit" value="Submit" class="button">
                <a href="#" class="button button-secondary">Cancel</a>
            </form>
        </div>
    </div>
<?php include __DIR__ . '/footer.phtml'; ?>